### ISSUE TITLE
checksum files for datasets

### ISSUE THREAD

**Issue by qianjiaqiang** [BioinfoMachineLearning/cryoppp#2]
we can check whether files have been updated on the ftp site and download updated file

**Comment by Ashwin-Dhakal** [comment]
> we can check whether files have been updated on the ftp site and download updated file

@qianjiaqiang , The file naming conventions in the EMPIAR repository remain unchanged, so there should be no discrepancies between the file names in the EMPIAR repository and the CryoPPP data.
