### ISSUE TITLE
No permission to access server

### ISSUE THREAD

**Issue by GlennXC** [BioinfoMachineLearning/cryoppp#4]
When I tried to download 10005 from https://calla.rnet.missouri.edu/cryoppp/10005.tar.gz, it said "Forbidden  You don't have permission to access /cryoppp/10005.tar.gz on this server."
It's same for other particle files.

**Comment by KiSchnelle** [comment]
Hello, same for me on the lite dataset

**Comment by kamzero** [comment]
Hello, I have encountered the same problem.

**Comment by rajangyawali** [comment]
This problem has been solved. Thanks for raising this issue

**Comment by kamzero** [comment]
> This problem has been solved. Thanks for raising this issue

Thanks :D

**Comment by XuChentianye** [comment]
Thanks a lot!

**Comment by SteadyPPP** [comment]
Thanks a lot!
